[0m13:51:27.393202 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102282790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b238d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104b23f90>]}


============================== 13:51:27.396376 | f6da5b4d-ce81-42bb-ab45-2d362863bceb ==============================
[0m13:51:27.396376 [info ] [MainThread]: Running with dbt=1.10.4
[0m13:51:27.396763 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt compile', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:51:27.397145 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/wildlife-streaming-e2e/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m13:51:27.404478 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_success": false, "command_wall_clock_time": 0.049263123, "process_in_blocks": "0", "process_kernel_time": 0.159305, "process_mem_max_rss": "108642304", "process_out_blocks": "0", "process_user_time": 0.6154}
[0m13:51:27.404875 [debug] [MainThread]: Command `dbt compile` failed at 13:51:27.404821 after 0.05 seconds
[0m13:51:27.405157 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10042d610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10058b190>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104aa3ed0>]}
[0m13:51:27.405431 [debug] [MainThread]: Flushing usage events
[0m13:51:28.036833 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:51:35.180481 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1124bc7d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1124bdbd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1124e3f50>]}


============================== 13:51:35.182717 | 1040ec41-bf58-43bd-9a5f-ff908820971c ==============================
[0m13:51:35.182717 [info ] [MainThread]: Running with dbt=1.10.4
[0m13:51:35.183093 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '.', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt compile --profiles-dir .', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:51:35.183458 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/wildlife-streaming-e2e/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m13:51:35.185123 [debug] [MainThread]: Resource report: {"command_name": "compile", "command_success": false, "command_wall_clock_time": 0.036811583, "process_in_blocks": "0", "process_kernel_time": 0.115056, "process_mem_max_rss": "108855296", "process_out_blocks": "0", "process_user_time": 0.591801}
[0m13:51:35.185496 [debug] [MainThread]: Command `dbt compile` failed at 13:51:35.185441 after 0.04 seconds
[0m13:51:35.185756 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1023dd790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1124bdad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10247da90>]}
[0m13:51:35.186003 [debug] [MainThread]: Flushing usage events
[0m13:51:35.682116 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:53:50.223248 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1136a0c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1136eb310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1136ebcd0>]}


============================== 22:53:50.226871 | ce57ebce-a18c-4812-a007-bd080dc923cb ==============================
[0m22:53:50.226871 [info ] [MainThread]: Running with dbt=1.10.4
[0m22:53:50.227283 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/linhnguyen/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m22:53:50.227691 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/wildlife-streaming-e2e/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m22:53:50.230021 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04429829, "process_in_blocks": "0", "process_kernel_time": 0.164832, "process_mem_max_rss": "112066560", "process_out_blocks": "0", "process_user_time": 0.660577}
[0m22:53:50.230346 [debug] [MainThread]: Command `dbt run` failed at 22:53:50.230297 after 0.04 seconds
[0m22:53:50.230612 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1045adc90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1136ffbd0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1136c7f50>]}
[0m22:53:50.230854 [debug] [MainThread]: Flushing usage events
[0m22:53:50.753608 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:53:58.497645 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11236d650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11236d410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112374610>]}


============================== 22:53:58.500002 | 93cc1da9-38cf-4283-8ca3-256a9f62bfaa ==============================
[0m22:53:58.500002 [info ] [MainThread]: Running with dbt=1.10.4
[0m22:53:58.500414 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': '.', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run --profiles-dir .', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:53:58.500810 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/wildlife-streaming-e2e/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m22:53:58.502665 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.038822956, "process_in_blocks": "0", "process_kernel_time": 0.128826, "process_mem_max_rss": "113704960", "process_out_blocks": "0", "process_user_time": 0.649454}
[0m22:53:58.503046 [debug] [MainThread]: Command `dbt run` failed at 22:53:58.502996 after 0.04 seconds
[0m22:53:58.503305 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1123ebe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1006f1d50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1121256d0>]}
[0m22:53:58.503544 [debug] [MainThread]: Flushing usage events
[0m22:53:58.981730 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m22:54:03.455677 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1198cbf10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1198eb850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1198ebf90>]}


============================== 22:54:03.458794 | 02ad1b0c-f7ea-4240-ba7c-ed3e9492c57e ==============================
[0m22:54:03.458794 [info ] [MainThread]: Running with dbt=1.10.4
[0m22:54:03.459219 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': './dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run --profiles-dir ./dbt', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:54:03.459652 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/wildlife-streaming-e2e/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m22:54:03.461401 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.04540425, "process_in_blocks": "0", "process_kernel_time": 0.126569, "process_mem_max_rss": "115228672", "process_out_blocks": "0", "process_user_time": 0.661826}
[0m22:54:03.461718 [debug] [MainThread]: Command `dbt run` failed at 22:54:03.461669 after 0.05 seconds
[0m22:54:03.461987 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1198c7b90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1198c7d50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x100fbdd50>]}
[0m22:54:03.462223 [debug] [MainThread]: Flushing usage events
[0m22:54:03.947209 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:00:03.259648 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11cacbd90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11caa1410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11cae7fd0>]}


============================== 23:00:03.262391 | 03467528-0659-47da-9d30-74097e7ecf04 ==============================
[0m23:00:03.262391 [info ] [MainThread]: Running with dbt=1.10.4
[0m23:00:03.262841 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/linhnguyen/.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m23:00:03.263249 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/wildlife-streaming-e2e/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m23:00:03.265149 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.040888168, "process_in_blocks": "0", "process_kernel_time": 0.137913, "process_mem_max_rss": "114409472", "process_out_blocks": "0", "process_user_time": 0.658394}
[0m23:00:03.265534 [debug] [MainThread]: Command `dbt run` failed at 23:00:03.265473 after 0.04 seconds
[0m23:00:03.265823 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102df1c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11caffe10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11cafff10>]}
[0m23:00:03.266068 [debug] [MainThread]: Flushing usage events
[0m23:00:03.753647 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m23:29:17.290918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113825810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113825c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113ae7610>]}


============================== 23:29:17.294539 | b5222704-9161-4385-a6e1-ce16fd7e549a ==============================
[0m23:29:17.294539 [info ] [MainThread]: Running with dbt=1.10.4
[0m23:29:17.295098 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': '/Users/linhnguyen/.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m23:29:17.295579 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/wildlife-streaming-e2e/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m23:29:17.297918 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.046166543, "process_in_blocks": "0", "process_kernel_time": 0.160935, "process_mem_max_rss": "113754112", "process_out_blocks": "0", "process_user_time": 0.665719}
[0m23:29:17.298324 [debug] [MainThread]: Command `dbt run` failed at 23:29:17.298268 after 0.05 seconds
[0m23:29:17.298622 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1042f5d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x113affe50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104395fd0>]}
[0m23:29:17.298885 [debug] [MainThread]: Flushing usage events
[0m23:29:17.907134 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:01:27.981517 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c2ca3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c2e7c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c2e7f90>]}


============================== 00:01:27.985238 | 5393a671-24d1-4450-8945-9bde46668e4c ==============================
[0m00:01:27.985238 [info ] [MainThread]: Running with dbt=1.10.4
[0m00:01:27.985702 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/linhnguyen/.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:01:27.986126 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/linhnguyen/visual_code/linh/wildlife-streaming-e2e/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml

[0m00:01:27.988150 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.05688925, "process_in_blocks": "0", "process_kernel_time": 0.159098, "process_mem_max_rss": "113770496", "process_out_blocks": "0", "process_user_time": 0.67013}
[0m00:01:27.988532 [debug] [MainThread]: Command `dbt run` failed at 00:01:27.988482 after 0.06 seconds
[0m00:01:27.988804 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1043d9c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10c2c8890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10462fb10>]}
[0m00:01:27.989051 [debug] [MainThread]: Flushing usage events
[0m00:01:28.542031 [debug] [MainThread]: An error was encountered while trying to flush usage events
